service: aglet-backend

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1  # Change to your preferred AWS region

functions:
  app:
    handler: serverless-http
    events:
      - http:
          path: /{proxy+}
          method: any
      - http:
          path: /webhooks
          method: post

plugins:
  - serverless-offline
